// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "baseURL": string;
      "apiKey": string;
      "model": string;
      "tagSource": string;
      "maxTags": number;
      "temperature": string;
      "includeFullText": boolean;
      "maxFullTextLength": number;
      "tagPrefixFilter": string;
      "systemPrompt": string;
      "confirmationMode": boolean;
      "concurrency": number;
      "requestInterval": number;
    };
  }
}
